model:
  model_name_or_path: "liuhaotian/llava-v1.5-7b"
  model_type: "llava"
  use_vllm: false
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.85
  max_model_len: 4096
  use_lora: true
  lora_r: 128
  lora_alpha: 256
dataset:
  data_path: "src/datasets/data"
  image_dir: "data/images/COCO2017"
training:
  output_dir: "./outputs/llava"
  num_epochs: 10
  batch_size: 8
  gradient_accumulation_steps: 1
  patience: 10
  learning_rate: 2e-4
