model:
  model_name_or_path: "Salesforce/blip-vqa-base"
  model_type: "blip-vqa-base"
  use_lora: false
dataset:
  data_path: "src/datasets/data"
  image_dir: "data/images/COCO2017"
training:
  output_dir: "./outputs/blip"
  num_epochs: 30
  batch_size: 8
  patience: 5
  learning_rate: 6.0e-07
