model:
  model_name_or_path: "Salesforce/instructblip-flan-t5-xl"
  model_type: "instructblip"
  use_lora: true
  lora_r: 16
dataset:
  data_path: "src/datasets/data"
  image_dir: "data/images"
training:
  output_dir: "./outputs/instructblip"
  num_epochs: 30
  batch_size: 8
  patience: 5
  learning_rate: 4.0e-05
