model:
  model_name_or_path: "MAGAer13/mplug-owl-llama-7b"
  model_type: "mplug"
  use_lora: true
  lora_r: 16
dataset:
  data_path: "src/datasets/data"
  image_dir: "data/images"
training:
  output_dir: "./outputs/mplug_owl"
  num_epochs: 10
  batch_size: 8
  patience: 10
  learning_rate: 5.0e-05
