model:
  model_name_or_path: "spacellava"
  model_type: "spacellava"
  use_lora: true
  lora_r: 128
dataset:
  data_path: "data/train.jsonl"
  image_dir: "data/images"
training:
  output_dir: "./outputs/spacellava"
  num_epochs: 10
  batch_size: 8
  patience: 10
  learning_rate: 2.0e-04
